# Generated by Django 3.1.2 on 2020-12-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201210_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseCoverPic',
            field=models.ImageField(default='images/thumbnail.jpg', upload_to='images'),
        ),
    ]
