# Generated by Django 3.1.2 on 2020-12-19 15:03

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_coursecoverpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseCoverPic',
            field=models.ImageField(default='images/thumbnail.jpg', upload_to=courses.models.Course.userDirectory),
        ),
    ]
