# Generated by Django 3.1.2 on 2020-12-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201205_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='bees',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bees',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
