# Generated by Django 3.1.2 on 2020-12-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201205_0601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bees',
        ),
    ]
