# Generated by Django 3.1.2 on 2020-12-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_bees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
